name: Install Windows Features

on:
  push:
    branches: [main]

jobs:
  install_features:
    # Specify the labels to use your specific runner
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set Up Python Environment
        run: |
          python -m pip install --upgrade pip
          pip install ansible[azure]
          
      - name: Run Ansible Playbook
        shell: cmd
        env:
          # Azure authentication using a user-assigned managed identity
          AZURE_USE_MSI: "true"
          AZURE_MANAGED_IDENTITY_ID: ${{ secrets.AZURE_MANAGED_IDENTITY_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Credentials for connecting to the target Windows VMs (via WinRM or similar)
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          PYTHONUTF8: "1"            # Force Python to use UTF-8 encoding
          PYTHONIOENCODING: "utf-8"    # Force Python to use UTF-8 encoding
          LANG: "en_US.UTF-8"          # Set locale variables
          LC_ALL: "en_US.UTF-8"
        run: |
          chcp 65001
          python -X utf8 -m ansible.cli.playbook -i inventory/azure_rm.yml playbook.yml
