name: Install Windows Features

on:
  push:
    branches: [main]

jobs:
  install_features:
    # Specify the labels to use your specific runner
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set Up Python Environment
        run: |
          python -m pip install --upgrade pip
          pip install ansible[azure]
          
      - name: Run Ansible Playbook
        env:
          # Azure authentication using a user-assigned managed identity
          AZURE_USE_MSI: "true"
          AZURE_MANAGED_IDENTITY_ID: ${{ secrets.AZURE_MANAGED_IDENTITY_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Credentials for connecting to the target Windows VMs (via WinRM or similar)
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          PYTHONIOENCODING: "utf-8"    # Force Python to use UTF-8 encoding
        run: |
          ansible-playbook playbook.yml -i inventory/azure_rm.yml
