name: Install Windows Features

on:
  push:
    branches: [main]

jobs:
  install_features:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pip for Python3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

      - name: Set Up Python Environment
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible[azure]

      - name: Run Ansible Playbook
        env:
          # Azure authentication using a user-assigned managed identity
          AZURE_USE_MSI: "true"
          AZURE_MANAGED_IDENTITY_ID: ${{ secrets.AZURE_MANAGED_IDENTITY_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Credentials for connecting to the target Windows VMs (via WinRM)
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
        run: |
          ansible-playbook playbook.yml -i inventory/azure_rm.yml
