name: Install Windows Features

on:
  push:
    branches: [main]

jobs:
  install_features:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip

      - name: Set Up Python Virtual Environment and Install Ansible
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip --break-system-packages
          pip install ansible[azure] pywinrm
          ansible-galaxy collection install azure.azcollection

      - name: Run Ansible Playbook
        env:
          AZURE_USE_MSI: "true"
          AZURE_MANAGED_IDENTITY_ID: ${{ secrets.AZURE_MANAGED_IDENTITY_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
        run: |
          source venv/bin/activate
          ansible-playbook playbook.yml -i inventory/static_windows.ini
